# Generated by Django 6.0.6 on 2026-07-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('classes', models.ManyToManyField(blank=True, related_name='teachers', to='students.schoolclass')),
            ],
        ),
    ]
